package Server_Java.WordyApp;


/**
* WordyApp/WordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public abstract class WordyPOA extends org.omg.PortableServer.Servant
 implements WordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new Integer (0));
    _methods.put ("signOut", new Integer (1));
    _methods.put ("startGame", new Integer (2));
    _methods.put ("requestLetters", new Integer (3));
    _methods.put ("sendWord", new Integer (4));
    _methods.put ("checkTime", new Integer (5));
    _methods.put ("getRoundWinner", new Integer (6));
    _methods.put ("getGameWinner", new Integer (7));
    _methods.put ("checkReadyStatus", new Integer (8));
    _methods.put ("getTopPlayers", new Integer (9));
    _methods.put ("getTopWords", new Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordyApp/Wordy/login
       {
         try {
           String name = in.read_string ();
           String password = in.read_string ();
           String $result = null;
           $result = this.login (name, password);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (usernameMismatch $ex) {
           out = $rh.createExceptionReply ();
           usernameMismatchHelper.write (out, $ex);
         } catch (alreadyLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           alreadyLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordyApp/Wordy/signOut
       {
         String username = in.read_string ();
         this.signOut (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordyApp/Wordy/startGame
       {
         try {
           String username = in.read_string ();
           boolean $result = false;
           $result = this.startGame (username);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (playersNotFound $ex) {
           out = $rh.createExceptionReply ();
           playersNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // WordyApp/Wordy/requestLetters
       {
         String username = in.read_string ();
         String $result[] = null;
         $result = this.requestLetters (username);
         out = $rh.createReply();
         lettersHelper.write (out, $result);
         break;
       }

       case 4:  // WordyApp/Wordy/sendWord
       {
         try {
           String username = in.read_string ();
           String word = in.read_string ();
           String $result = null;
           $result = this.sendWord (username, word);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (invalidWordLength $ex) {
           out = $rh.createExceptionReply ();
           invalidWordLengthHelper.write (out, $ex);
         } catch (invalidWord $ex) {
           out = $rh.createExceptionReply ();
           invalidWordHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // WordyApp/Wordy/checkTime
       {
         String username = in.read_string ();
         int interval = in.read_long ();
         boolean $result = false;
         $result = this.checkTime (username, interval);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // WordyApp/Wordy/getRoundWinner
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getRoundWinner (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // WordyApp/Wordy/getGameWinner
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getGameWinner (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // WordyApp/Wordy/checkReadyStatus
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.checkReadyStatus (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // WordyApp/Wordy/getTopPlayers
       {
         String $result[][] = null;
         $result = this.getTopPlayers ();
         out = $rh.createReply();
         playerWinsHelper.write (out, $result);
         break;
       }

       case 10:  // WordyApp/Wordy/getTopWords
       {
         String $result[][] = null;
         $result = this.getTopWords ();
         out = $rh.createReply();
         playerWordsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordyApp/Wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Wordy _this()
  {
    return WordyHelper.narrow(
    super._this_object());
  }

  public Wordy _this(org.omg.CORBA.ORB orb)
  {
    return WordyHelper.narrow(
    super._this_object(orb));
  }


} // class WordyPOA
